"""Sweep the margin gate for a frozen normalized-image reranker."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Iterable

import torch
from torch.utils.data import DataLoader

from mnist_ssl.paths import MODELS_DIR, OUT_DIR

from .nonlinear_probe import file_sha256
from .normalized_image_reranker import (
    DEFAULT_IMAGE_CACHE,
    DEFAULT_LINEAR_PROBE,
    IndependentNormalizedReranker,
    NormalizedImagePairDataset,
    build_or_load_normalized_images,
    gated_predictions,
    reranking_metrics,
    score_dataset,
)
from .train import pick_device


DEFAULT_RERANKER = (
    OUT_DIR
    / "dinov2_normalized_image_reranker_50ep"
    / "milestone_epoch45.pt"
)
DEFAULT_PAIRS = (
    OUT_DIR
    / "dinov2_normalized_image_reranker_50ep"
    / "training_pairs.pt"
)
DEFAULT_OUTPUT = (
    OUT_DIR
    / "dinov2_normalized_image_reranker_50ep"
    / "training_threshold_sweep_epoch45.json"
)
DEFAULT_BACKBONE = (
    MODELS_DIR / "dinov2_mnist_augmented_cls_150ep_epoch0075.pt"
)


def _candidate_predictions(
    base_top1: torch.Tensor,
    base_top2: torch.Tensor,
    scores: torch.Tensor,
) -> torch.Tensor:
    rows = torch.arange(len(base_top1))
    candidates = torch.stack((base_top1, base_top2), dim=1)
    candidate_scores = scores[rows[:, None], candidates]
    return candidates[rows, candidate_scores.argmax(dim=1)]


def exact_best_threshold(
    *,
    labels: torch.Tensor,
    base_top1: torch.Tensor,
    base_top2: torch.Tensor,
    normalized_margin: torch.Tensor,
    reranker_scores: torch.Tensor,
) -> float:
    """Return the observed-margin threshold with the largest error reduction."""

    candidate = _candidate_predictions(base_top1, base_top2, reranker_scores)
    base_correct = base_top1.eq(labels)
    candidate_correct = candidate.eq(labels)
    gain = (
        (~base_correct & candidate_correct).to(torch.int64)
        - (base_correct & ~candidate_correct).to(torch.int64)
    )
    order = normalized_margin.argsort(stable=True)
    ordered_margin = normalized_margin[order]
    cumulative_gain = gain[order].cumsum(dim=0)
    group_end = torch.ones(len(order), dtype=torch.bool)
    group_end[:-1] = ordered_margin[:-1].ne(ordered_margin[1:])
    grouped_gain = cumulative_gain[group_end]
    grouped_margin = ordered_margin[group_end]

    # Threshold zero represents no gate when all observed margins are positive.
    best_gain = torch.tensor(0, dtype=torch.int64)
    best_threshold = 0.0
    index = int(grouped_gain.argmax().item())
    if grouped_gain[index] > best_gain:
        best_threshold = float(grouped_margin[index].item())
    return best_threshold


def metrics_at_threshold(
    threshold: float,
    *,
    labels: torch.Tensor,
    base_top1: torch.Tensor,
    base_top2: torch.Tensor,
    normalized_margin: torch.Tensor,
    reranker_scores: torch.Tensor,
) -> dict[str, Any]:
    predictions = gated_predictions(
        base_top1,
        base_top2,
        normalized_margin,
        reranker_scores,
        gate_threshold=threshold,
    )
    return reranking_metrics(
        predictions,
        labels=labels,
        base_top1=base_top1,
        base_top2=base_top2,
        normalized_margin=normalized_margin,
        gate_threshold=threshold,
    )


def run(args: argparse.Namespace) -> dict[str, Any]:
    if args.output.exists():
        raise FileExistsError(f"refusing to overwrite {args.output}")

    device = torch.device(args.device) if args.device else pick_device()
    pairs = torch.load(args.pairs, map_location="cpu", weights_only=False)
    signature = pairs.get("signature", {})
    if signature.get("linear_probe_sha256") != file_sha256(args.linear_probe):
        raise ValueError("pair metadata was not generated by the requested probe")
    if signature.get("linear_probe_type") != "Linear(128,10)":
        raise ValueError("pair metadata does not use the linear probe")
    if signature.get("linear_probe_epochs") != 50:
        raise ValueError("pair metadata does not use the 50-epoch probe")

    labels = pairs["label"].long()
    images, _ = build_or_load_normalized_images(args.image_cache, labels)
    dataset = NormalizedImagePairDataset(
        images,
        labels,
        pairs["hardest_wrong"],
    )
    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=0,
    )

    checkpoint = torch.load(args.reranker, map_location=device, weights_only=False)
    if checkpoint.get("completed_epoch") != 45:
        raise ValueError("threshold sweep requires the selected epoch-45 reranker")
    config = checkpoint["config"]
    model = IndependentNormalizedReranker(
        channels=tuple(config["channels"]),
        dropout=config["dropout"],
    ).to(device)
    model.load_state_dict(checkpoint["model_state_dict"])
    reranker_scores, pair_accuracy = score_dataset(model, loader, device)

    fields = {
        "labels": labels,
        "base_top1": pairs["linear_top1"],
        "base_top2": pairs["linear_top2"],
        "normalized_margin": pairs["normalized_margin"],
        "reranker_scores": reranker_scores,
    }
    best_exact_threshold = exact_best_threshold(**fields)
    dense_thresholds = torch.arange(
        args.grid_min,
        args.grid_max + args.grid_step / 2,
        args.grid_step,
        dtype=torch.float64,
    ).tolist()
    grid = [metrics_at_threshold(float(threshold), **fields) for threshold in dense_thresholds]
    best_grid = max(
        grid,
        key=lambda row: (
            row["net_error_reduction"],
            -row["new_errors"],
            -row["gate_eligible"],
        ),
    )
    exact_best = metrics_at_threshold(best_exact_threshold, **fields)

    requested_thresholds = sorted(
        set(args.report_thresholds + [best_grid["gate_threshold"], best_exact_threshold])
    )
    report_rows = [
        metrics_at_threshold(float(threshold), **fields)
        for threshold in requested_thresholds
    ]
    result = {
        "protocol": {
            "dataset": "MNIST train, all 60,000 examples, in-sample",
            "threshold_selection": "training-set threshold tuning; no folds",
            "linear_probe": str(args.linear_probe),
            "linear_probe_sha256": file_sha256(args.linear_probe),
            "linear_probe_type": "Linear(128,10)",
            "linear_probe_epochs": 50,
            "backbone": str(args.backbone),
            "backbone_sha256": file_sha256(args.backbone),
            "reranker": str(args.reranker),
            "reranker_sha256": file_sha256(args.reranker),
            "reranker_epoch": checkpoint["completed_epoch"],
            "gate_normalization": "top-two gap / per-sample std of ten logits",
            "reranker_inputs": "bbox-normalized MNIST pixels only",
            "grid_min": args.grid_min,
            "grid_max": args.grid_max,
            "grid_step": args.grid_step,
        },
        "reranker_pair_accuracy": pair_accuracy,
        "best_grid": best_grid,
        "best_exact_observed_margin": exact_best,
        "report_rows": report_rows,
        "grid": grid,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2) + "\n")

    header = (
        "threshold  gated  recoverable  changed  fixes  breaks  wrong2wrong  "
        "net  errors  accuracy"
    )
    print(header, flush=True)
    for row in report_rows:
        print(
            f"{row['gate_threshold']:9.6f} "
            f"{row['gate_eligible']:6d} "
            f"{row['gate_top2_recoverable']:11d} "
            f"{row['changed_predictions']:8d} "
            f"{row['fixed_errors']:6d} "
            f"{row['new_errors']:7d} "
            f"{row['wrong_to_wrong']:11d} "
            f"{row['net_error_reduction']:4d} "
            f"{row['reranked_errors']:7d} "
            f"{100 * row['reranked_accuracy']:8.4f}%",
            flush=True,
        )
    print(
        f"best_grid_threshold={best_grid['gate_threshold']:.6f} "
        f"net={best_grid['net_error_reduction']} "
        f"errors={best_grid['reranked_errors']}",
        flush=True,
    )
    print(
        f"best_exact_threshold={exact_best['gate_threshold']:.9f} "
        f"net={exact_best['net_error_reduction']} "
        f"errors={exact_best['reranked_errors']}",
        flush=True,
    )
    print(f"output={args.output}", flush=True)
    return result


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--linear-probe", type=Path, default=DEFAULT_LINEAR_PROBE)
    parser.add_argument("--backbone", type=Path, default=DEFAULT_BACKBONE)
    parser.add_argument("--reranker", type=Path, default=DEFAULT_RERANKER)
    parser.add_argument("--pairs", type=Path, default=DEFAULT_PAIRS)
    parser.add_argument("--image-cache", type=Path, default=DEFAULT_IMAGE_CACHE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--batch-size", type=int, default=1024)
    parser.add_argument("--device", type=str)
    parser.add_argument("--grid-min", type=float, default=0.0)
    parser.add_argument("--grid-max", type=float, default=3.0)
    parser.add_argument("--grid-step", type=float, default=0.001)
    parser.add_argument(
        "--report-thresholds",
        type=float,
        nargs="+",
        default=[
            0.0,
            0.01,
            0.02,
            0.0367,
            0.05,
            0.075,
            0.1,
            0.15,
            0.2,
            0.3,
            0.5,
            0.75,
            1.0,
            1.5,
            2.0,
            3.0,
        ],
    )
    return parser.parse_args(argv)
